### ISSUE TITLE
SSRF in `img_proxy_fetch` RPC method

### ISSUE THREAD

**Issue by Fitblip** [Cryptonomic/ImageProxy#4]
Hi folks, I saw you post an update about this project recently and it seemed like a neat tool! Rust seems like a good language for a thing like this for sure :).

In another life I wear an application security/secure development hat and so I did a bit of kicking the tires and found a [SSRF](https://portswigger.net/web-security/ssrf) issue in the `img_proxy_fetch` RPC method. Specifying the `force` function bypasses the content type checking logic and will blindly make http/https/ipfs requests unrestricted. Let me know if you want more details about how this sort of issue can be abused.

https://github.com/Cryptonomic/ImageProxy/blob/337e2d8d2951deeab756843ec3650e741e5a286f/src/rpc/mod.rs#L39-L44

Ideally you'd do the same content-type checking there which would help mitigate a lot of the impact from this issue

https://github.com/Cryptonomic/ImageProxy/blob/337e2d8d2951deeab756843ec3650e741e5a286f/src/rpc/mod.rs#L85-L92

---

Since you have a specific workflow-focused proxy here where you only want to be proxying images of a specific type, doing content checking is a great way to stop SSRF from ever being an issue in terms of reflecting data back to an attacker. 

That said you also want to be wary of forced requests originating from your app even without reflecting content back to people since they can lead to interactions with locally running (and otherwise properly firewalled/isolated) services that respond to badly formatted input. Services like Redis or Varnish will happily execute a request to drop all databases or clear caches (or worse!), even buried in an otherwise valid HTTP request that happens to arrive on the proper port. 

Preventing this is unfortunately a bit cumbersome but I recommend:
- Parsing the URI specified to extract the hostname/ip address
- If it's an IP address, ensure it's not in the reserved or loopback ranges (basically anything labeled "private network", "subnet", or "host" on this list https://en.wikipedia.org/wiki/Reserved_IP_addresses#IPv4), and don't make the request if it is. `169.254.169.254` is the hetzner cloud metadata service address and considered private space, for example.
- If it's a domain, resolve it to an ip address before making the request, and do the above check for reserved IP ranges
- Ensure you don't follow redirects (3XX status codes) automatically

If you have any questions def feel free to reach out at ryan@hover.engineering or we're probably both in the `tezos-dev` slack server too!

**Comment by Taaseen-Ali** [comment]
Thank you for pointing out this vulnerability @Fitblip. We've gone ahead and fixed this issue with #16. Feel free to take a look!
