### ISSUE TITLE
Add "data" parameter to request

### ISSUE THREAD

**Issue by Taaseen-Ali** [Cryptonomic/ImageProxy#6]
Currently the proxy returns a json response if the image is blocked and the raw bytes of the image if it is not. Allow the user to specify if they want a json response if the image is allowed as well. i.e.:

Request:
```
{
    data:"json"|"raw"...
}
```

Response (if json):
```
{... 
    categories: [...],
    data: "data/png:....".
}
```

Response (if raw)
```
"data/png...."
```

**Comment by bhaskarkishore** [comment]
Available as property `response_type` in `fetch` requests starting version `1.1.0` or higher.
